language:
  - swift

os:
  - osx

osx_image:
  - xcode12.2

script:
  - swift package generate-xcodeproj
  - xcodebuild test -scheme BitBay-Ticker -destination platform="macOS" -enableCodeCoverage YES

after_success:
  - bash <(curl -s https://codecov.io/bash)
